"""team to teams multiple

Revision ID: 1fdb275a65a5
Revises: ef6b72f2fed6
Create Date: 2025-10-07 19:24:25.842239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdb275a65a5'
down_revision = 'ef6b72f2fed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID команды'))
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'])
    op.drop_table('team_members')
    # ### end Alembic commands ###
