"""second

Revision ID: e9ad72f03c10
Revises: 5fad9aae7069
Create Date: 2025-10-02 15:12:34.513706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9ad72f03c10'
down_revision = '5fad9aae7069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Название команды',
               existing_nullable=False)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               comment='Описание команды',
               existing_nullable=True)
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Код приглашения',
               existing_nullable=True)
    op.alter_column('teams', 'owner_id',
               existing_type=sa.UUID(),
               comment='ID владельца',
               existing_nullable=True)
    op.alter_column('teams', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор записи',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('teams_id_seq'::regclass)"))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания записи',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата последнего обновления',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Фамилия пользователя',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'MANAGER', 'ADMIN', name='userrole'),
               comment='Роль пользователя',
               existing_nullable=True)
    op.alter_column('users', 'team_id',
               existing_type=sa.INTEGER(),
               comment='ID команды',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата обновления',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата обновления',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата создания',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID команды',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'MANAGER', 'ADMIN', name='userrole'),
               comment=None,
               existing_comment='Роль пользователя',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Фамилия пользователя',
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата последнего обновления',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата создания записи',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор записи',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('teams_id_seq'::regclass)"))
    op.alter_column('teams', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID владельца',
               existing_nullable=True)
    op.alter_column('teams', 'invite_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Код приглашения',
               existing_nullable=True)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание команды',
               existing_nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Название команды',
               existing_nullable=False)
    # ### end Alembic commands ###
