"""add password field

Revision ID: ef6b72f2fed6
Revises: e9ad72f03c10
Create Date: 2025-10-07 17:41:31.510813

"""


# revision identifiers, used by Alembic.
revision = 'ef6b72f2fed6'
down_revision = 'e9ad72f03c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
